name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_URL: ${{ secrets.DB_URL }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build (skip tests)
        run: mvn -B clean package -DskipTests=true

      - name: Upload entire project directory
        uses: actions/upload-artifact@v4
        with:
          name: project-files
          path: .

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download project files
        uses: actions/download-artifact@v4
        with:
          name: project-files
          path: project

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests
        working-directory: ./project
        run: mvn -B test

  push-registry:
    needs: test
    name: Push to Registry
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
          ibmcloud plugin install -f container-registry

      - name: Authenticate with IBM Cloud CLI
        run: |
          ibmcloud login --apikey ${{ secrets.IBM_CLOUD_API_KEY }} -r us-south -g Default
          ibmcloud cr region-set us-south
          ibmcloud cr login

      - name: Build with Docker
        run: |
          docker build -t us.icr.io/udla-applications-cr/management-microservice:${{ github.sha }} .

      - name: Push the image to ICR
        run: |
          docker push us.icr.io/udla-applications-cr/management-microservice:${{ github.sha }}

  deploy:
    needs: push-registry
    name: Deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
          ibmcloud plugin install -f kubernetes-service
          ibmcloud plugin install -f container-registry

      - name: Authenticate with IBM Cloud CLI
        run: |
          ibmcloud login --apikey ${{ secrets.IBM_CLOUD_API_KEY }} -r us-south -g Default
          ibmcloud cr region-set us-south
          ibmcloud cr login

      - name: Deploy to IKS
        run: |
          ibmcloud ks cluster config --cluster udla-aplications-cluster
          kubectl config current-context
          kubectl create deployment management \
          --image=us.icr.io/udla-applications-cr/management-microservice:${{ github.sha }} --dry-run=client -o yaml > deployment.yaml
          kubectl apply -f deployment.yaml
          kubectl set env deployment/management \
            DB_URL="${{ secrets.DB_URL }}" DB_USER="${{ secrets.DB_USER }}" DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
          kubectl rollout status deployment/management
          kubectl create service loadbalancer management --tcp=8080:8080 --dry-run -o yaml > service.yaml
          kubectl apply -f service.yaml
          kubectl get services -o wide