apiVersion: apps/v1
kind: Deployment
metadata:
  name: management
spec:
  replicas: 2
  selector:
    matchLabels:
      name: management
  template:
    metadata:
      labels:
        name: management
    spec:
      containers:
      - name: management
        image: daviduyaguarij/backend-microservice:3ad9cb9fb4646e7957d38ab6507f6bd4b6ecd6d2
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DB_URL
          value: "your connection string"
        - name: DB_USER
          value: "your user"
        - name: DB_PASSWORD
          value: "your password"
