version: '3'

services:
  inventories:
    build:
      context: .
      dockerfile: dockerfile
    image: "${DOCKER_USERNAME}/backend-microservice:${GITHUB_SHA}"
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://inventory:3306/final-project?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER: root
      DB_PASSWORD: "@administration2025"
    restart: always
    depends_on:
      inventory:
        condition: service_healthy

  inventory:
   image: mysql:latest
   ports:
    - "3306:3306"
   volumes:
    - mysql_data:/var/lib/mysql
   environment:
    MYSQL_ROOT_PASSWORD: "@administration2025"
    MYSQL_PASSWORD: "@administration2025"
    MYSQL_DATABASE: final-project
   restart: always
   healthcheck:
    test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    timeout: 10s
    retries: 10
volumes:
 mysql_data: