apiVersion: v1
kind: Service
metadata:
  name: management-lb
  annotations: 
    service.beta.kubernetes.io/do-loadbalancer-http-idle-timeout-seconds: "400"
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  selector:
    name: management