apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: management
  name: management
spec:
  replicas: 2
  selector:
    matchLabels:
      name: management
  template:
    metadata:
      labels:
        name: management
    spec:
      containers:
      - name: management
        image: daviduyaguarij/backend-microservice:363b7d9aafa62467f98b29de7f6e43ff2ed497a8
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DB_URL
          value: "jdbc:mysql://inventory:3306/final-project?createDatabaseIfNotExist=true&serverTimezone=UTC"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          value: "@administration2025"